version: "3"

services:
  redis:
    image: redis:7.0-bookworm
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    entrypoint: redis-server --save 60 1 --loglevel warning

  mysql:
    image: mysql:8.0-debian
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  selenium:
    image: selenium/standalone-chrome:119.0
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - 4444:4444
      - 7900:7900

  alist:
    image: xhofe/alist:latest
    restart: unless-stopped
    ports:
      - 5244:5244
    volumes:
      - /etc/alist:/opt/alist/data
    environment:
      PUID: 0
      PGID: 0
      UMASK: 022

  aria2:
    image: p3terx/aria2-pro:latest
    restart: unless-stopped
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    volumes:
      - /etc/aria2:/config
      - $DATA_PWD/aria2-downloads:/downloads
    environment:
      PUID: 0
      PGID: 0
      UMASK: 022
      RPC_SECRET: $RPC_SECRET
      RPC_PORT: 6800
      LISTEN_PORT: 6888

  bilibili-download:
    build: ./bilibili_download
    restart: unless-stopped
    volumes:
      - /mnt/appdata/bilibili_download:/download
    environment:
      UPLOAD_URL: http://tele-upload:5000
      RUN_HOUR: 2,14,22

  lofter-download:
    build: ./lofter_download
    restart: unless-stopped
    volumes:
      - /mnt/appdata/lofter_download:/download
    environment:
      RUN_HOUR: 6
      HOMEPAGE_URL: $HOMEPAGE_URL

  qzone-download:
    build: ./QzoneCrawler
    restart: unless-stopped
    volumes:
      - /mnt/appdata/qzone_download:/download
    environment:
      QQ_ACCOUNT: $QQ_ACCOUNT
      QQ_PASSWORD: $QQ_PASSWORD
      RUN_HOUR: 5
      WEBDRIVER_URL: http://selenium:4444/wd/hub
      CLIENT_PROXY: 192.168.1.14:4567

  tele-upload:
    build: ./tele_upload
    restart: unless-stopped
    volumes:
      - /tmp:/tmp
    ports:
      - 5000:5000
    stdin_open: true
    tty: true

volumes:
  redis-data:
  mysql-data:
  mongo-data:
  mongo-configdb:
